# Generated by Django 5.0.4 on 2024-04-16 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0002_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tsc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('year', models.IntegerField()),
                ('batch_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameModel(
            old_name='UserProfile',
            new_name='Bia',
        ),
    ]
