# Generated by Django 5.0.4 on 2024-05-02 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0003_tsc_rename_userprofile_bia'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bia',
        ),
    ]
