# Generated by Django 5.0.4 on 2024-05-02 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0005_bia'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tsc',
        ),
    ]
