# Generated by Django 5.0.4 on 2024-05-02 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0007_tsc'),
    ]

    operations = [
        migrations.CreateModel(
            name='Placements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('company_name', models.CharField(max_length=100)),
                ('package', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('batch_name', models.CharField(max_length=100)),
                ('profile_image', models.ImageField(default='profile_images/default.jpg', upload_to='profile_images/')),
            ],
        ),
    ]
