# Generated by Django 5.0.4 on 2024-05-02 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0009_course_meal_dailymenu'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('Sunday', 'Sunday'), ('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday')], max_length=10)),
                ('breakfast', models.CharField(blank=True, max_length=100)),
                ('lunch', models.CharField(blank=True, max_length=100)),
                ('tea', models.CharField(blank=True, max_length=100)),
                ('dinner', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='DailyMenu',
        ),
        migrations.DeleteModel(
            name='Meal',
        ),
    ]
